{% set name = "pyiron_lammps" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_lammps-{{ version }}.tar.gz
  sha256: 6eb55c6006d8494ee63e58165c3dd64baf890b2ec040cb93af4b20f9fe9992b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - ase
    - atomistics
    - numpy
    - pandas
    - pylammpsmpi
    - pympipool
    - versioneer
    - toml
  run:
    - jinja2 >=2.11.3,<=3.1.3
    - python >=3.8
    - ase ==3.22.1
    - atomistics >=0.1.21,<=0.1.26
    - numpy >=1.26.0,<=1.26.4
    - pandas >=1.5.3,<=2.2.2
    - pylammpsmpi >=0.2.14,<=0.2.17
    - pympipool >=0.7.15,<=0.7.18

test:
  imports:
    - pyiron_lammps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_lammps
  summary: pyiron_lammps - calculate material properties for interatomic potentials
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
