{% set name = "pyiron_lammps" %}
{% set version = "0.2.0" %}
{% set sha256 = "a3a2dcc35f420d4fe5c303b8b6a757864dc494b1788c749656ed06322956cecc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - ase >=3.22.1
    - lammps >=2022.06.23  # [not win]
    - numpy >=1.23.5
    - pandas >=1.5.3
    - pathlib2 >=2.3.7.post1
    - pympipool >=0.2.0
    - scipy >=1.10.1
    - spglib >=2.0.2
    - sqsgenerator >=0.2

test:
  imports:
    - pyiron_lammps

about:
  home: https://github.com/pyiron/pyiron_lammps
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Lammps plugin for pyiron - an integrated development environment (IDE) for computational materials science.'
  description: |
    pyiron was initially developed in the Computational Materials Design department of Joerg Neugebauer at the
    Max Planck Insitut für Eisenforschung (Max Planck Insitute for iron research) as a framework for ab initio
    thermodynamics. In collaboration with the Interdisciplinary Centre for Advanced Materials Simulation (ICAMS)
    the framework was recently extended for high throughput applications resulting in the opensource release of
    pyiron.
  doc_url: https://pyiron.org
  dev_url: https://github.com/pyiron

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
