{% set name = "pyiron_lammps" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_lammps-{{ version }}.tar.gz
  sha256: 23652d9d254fff154657bf1afb84420e4c31166434e1892ae63553e300079205

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ase >=3.22.1
    - atomistics >=0.1.2
    - numpy >=1.26.0
    - pandas >=2.1.3
    - pylammpsmpi >=0.2.6
    - pympipool >=0.7.5

test:
  imports:
    - pyiron_lammps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_lammps
  summary: pyiron_lammps - calculate material properties for interatomic potentials
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
