{% set name = "pyiron_lammps" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_lammps-{{ version }}.tar.gz
  sha256: 4e8cec67ec0c54ec6119a67c226782f1ad178b7032d888f54f46a1a470e0d148

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - ase
    - atomistics
    - numpy
    - pandas
    - pylammpsmpi
    - pympipool
    - versioneer
    - toml
    - setuptools
  run:
    - h5py >=3.9.0,<=3.13.0
    - pyiron_base >=0.10.0,<=0.11.5
    - pyiron_snippets >=0.1.3,<=0.1.4
    - scipy >=1.11.1,<=1.15.2
    - executorlib ==0.0.1
    - jinja2 >=2.11.3,<=3.1.4
    - python >={{ python_min }}
    - ase >=3.22.1,<=3.24.0
    - atomistics >=0.1.21,<=0.1.32
    - numpy >=1.26.0,<=2.2.3
    - pandas >=2.0.3,<=2.2.3
    - pylammpsmpi ==0.2.24
    - pympipool >=0.7.15,<=0.7.18

test:
  imports:
    - pyiron_lammps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_lammps
  summary: pyiron_lammps - calculate material properties for interatomic potentials
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
