{% set name = "pyiron_lammps" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_lammps-{{ version }}.tar.gz
  sha256: 14b94247f6ce3c32691eb1fb2f2d4f4623b3eb79206c9a6caa6d89e1b85ae877

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioneer
    - toml
    - setuptools
    - scipy
    - ase
    - numpy
    - pandas
  run:
    - python >={{ python_min }}
    - scipy >=1.11.1,<=1.15.2
    - ase >=3.22.1,<=3.25.0
    - numpy >=1.26.0,<=2.2.4
    - pandas >=2.0.3,<=2.3.1

test:
  imports:
    - pyiron_lammps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_lammps
  summary: pyiron_lammps - calculate material properties for interatomic potentials
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
