{% set name = "pyiron_lammps" %}
{% set version = "0.2.1" %}
{% set sha256 = "10bc17e41a5a39a02d4b25bf78c2e80ba06966ac63980bcacd1ecf38ba1ad41f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - ase >=3.22.1
    - numpy >=1.23.5
    - pandas >=2.0.2
    - pathlib2 >=2.3.7.post1
    - pympipool >=0.5.6
    - pylammpsmpi >=0.2.1
    - scipy >=1.11.1
    - spglib >=2.0.2
    - sqsgenerator >=0.2
    - structuretoolkit >=0.0.8

test:
  imports:
    - pyiron_lammps

about:
  home: https://github.com/pyiron/pyiron_lammps
  license: BSD-3-Clause
  license_family: BSD
  license_file: 'LICENSE'
  summary: 'pyiron_lammps - calculate material properties for interatomic potentials'
  description: |
    pyiron_lammps - calculate material properties for interatomic potentials
  doc_url: https://pyiron.org
  dev_url: https://github.com/pyiron/pyiron_lammps

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
