{% set name = "pyiron_lammps" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_lammps-{{ version }}.tar.gz
  sha256: d1ce3e5f4b3a75b3f6f766834219ca7401fef02cb9b46d7ed6e99e6fcf285307

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - ase
    - atomistics
    - numpy
    - pandas
    - pylammpsmpi
    - pympipool
    - versioneer
    - toml
    - setuptools
  run:
    - executorlib ==0.0.1
    - jinja2 >=2.11.3,<=3.1.4
    - python >={{ python_min }}
    - ase >=3.22.1,<=3.23.0
    - atomistics >=0.1.21,<=0.1.32
    - numpy >=1.26.0,<=1.26.4
    - pandas >=1.5.3,<=2.2.2
    - pylammpsmpi ==0.2.24
    - pympipool >=0.7.15,<=0.7.18

test:
  imports:
    - pyiron_lammps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_lammps
  summary: pyiron_lammps - calculate material properties for interatomic potentials
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
