{% set name = "pyiron_lammps" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_lammps-{{ version }}.tar.gz
  sha256: b9e67440f8a612784af8803df1c550c154f13ab00edfafcef65a3f2ba385474e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioneer
    - toml
    - setuptools
    - h5py
    - scipy
    - ase
    - numpy
    - pandas
  run:
    - python >={{ python_min }}
    - h5py >=3.9.0,<=3.13.0
    - scipy >=1.11.1,<=1.15.2
    - ase >=3.22.1,<=3.24.0
    - numpy >=1.26.0,<=2.2.3
    - pandas >=2.0.3,<=2.2.3

test:
  imports:
    - pyiron_lammps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_lammps
  summary: pyiron_lammps - calculate material properties for interatomic potentials
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
