schema_version: 1

context:
  name: pyiron_lammps
  version: "0.4.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyiron_lammps-${{ version }}.tar.gz
  sha256: 113fbd7c6fcddd73125eb4fbf42a63679c1d5b36318dd168d98345c4ca6c0010

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
    - scipy
    - ase
    - numpy
    - pandas
  run:
    - python >=${{ python_min }}
    - scipy >=1.11.1,<=1.16.2
    - ase >=3.22.1,<=3.26.0
    - numpy >=1.26.0,<=2.3.3
    - pandas >=2.0.3,<=2.3.3

tests:
  - python:
      imports:
        - pyiron_lammps
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: pyiron_lammps - calculate material properties for interatomic potentials
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/pyiron_lammps

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
