travis:
  secure:
    BINSTAR_TOKEN: ypYLLimKpf7gOWzcERU2eyCnR4I47k6NvaSwmOi0LpBMw9RiNWBTZkEYtMpjOIHBiYQkfFEVUBnycyMStjXfMvcyNrJ2Dqg07JTre+qhqVPnZFvwOgP2dPoCLmgUB3aQrPX8NIG8gBcnkP4HkNcWH8HQJU9KYPB1LDsR9DkpQniEoh2eoOQmwfvT7mGYmaqZEoG6oiQJigegBhXTnaESyZKtdM+/6c0PnDvfdtU4Byv904bu67MNkzSlv0esXFCUfTvCcGI2Q/myzl7u0VPVkI6Lk4y/GzCnPvGmyh6mVJR+L7fN58aEi6XXcxdO/b3aROLyoevUAB2UaX+LS1RW+IpQx51lPsq4sMPYRBXOJXDcx/pws6Z+MlHaaRCGR3yDfDrAAB+pTnFXl70KPppTRYZv31n3iSGduO9A8BkNedl1I1lwKTnVJRdOnxCnVB51LG2GOVcXIRNJ0XJTFwSy00AxTYW7TZryctNNE+4bCZDRlk+PLAG7rs+AUuvMDO/nYwzziGB8H00UxGoQ/WZTZteHs9nQeix1MkMWwzfjSODQ0BYvfvlysBMUHHe36dOgV8DKw8tcFx6zz3XSEbdwmRL3rJVpSQHL64AYI3sCw3RdS8opwiLazmOs2/XRkNRhpAGxo7dwZJiZQleONohcj7OnPUigILW6HgcV4X+aii8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
