travis:
  secure:
    BINSTAR_TOKEN: vf0KU6aRErwKIV3s64ndvAJnl2osS0fdc/4PA/1EuamGO9ALsJ/LzMcP/ZJNC4Bz6/7tE9LAaaR2jrQ7JVlX3N5zdY+1EQv5gNU6vkgSZL5uLn2l/rDbA1dRI/kY1iSg3ro+C/MDGnKYO56Wao5FuATv93dn+Ml52DkPnRcmrTAZ9LP1HqrfIJAhO+XZe4WtyXx61Lkh85TazvmrYMIc1fVJ2sRUG4Y2gGMfPMVDT61q5qlVeeKiSiXOSOTeyHwJA39ItBKw36F7iBgBF0v0kf6vBOpVMJg4mOVPidet4ZE0obSTDeKMD0ThOw//JLpwbVdgR7z2P3o6Ttq2YDO3pWSOy6xXpjlPHiuJnjzaay/OqhWsURvTHEfXzO+qJ/7F4rGXdx+DjdC43vSn7Ep1O+L2WX0e4qV9mLKt2E5BhHhAsLDafo/3bdCuc9sIPhGDitQdUrAvNociJse/uJa800C7rXov+DO2kQ0MNmShyX9nDa9vgvyKQXzplP4TBup2T3sp3foC0eHaPS3vjQhY4WoFAfUYQNp1+jLv2bvTBsIBeFWYfEnMBRJaX5/22aLmrJTh0w4FJBR97mDG1WRpFFZpmueifzK0mwn9p/35hPYEjUoM3LqmoVxe58coAo3qDIRs6YpyOZu16vvkqAMq/DkbZLAmD/xLDyWO1Wawni4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
